### ISSUE TITLE
sonarr-update-tba.bash: support Sonarr API v4

### ISSUE THREAD

**Issue by schumi4** [goose-ws/bash-scripts#3]
HI,

did what the script told me:
`Please create an issue for support with over API versions`

Would really like to implement this script, thank you in advance!

**Comment by goose-ws** [comment]
That's a typo, should be "other", not "over".

What version of sonarr are you using? Is it in docker?

**Comment by schumi4** [comment]
It's the v4 beta, image is `lscr.io/linuxserver/sonarr:develop`.

**Comment by goose-ws** [comment]
Ok. Probably won't work on it today (Happy Thanksgiving, if you celebrate it!), but Friday or Saturday I'll work on adding support for v4.

**Comment by goose-ws** [comment]
Didn't mean to autoclose with my commit message. I've made a commit that should fix it, please let me know if it works for you or not, as I'm still on v3 and can't test it myself.

**Comment by schumi4** [comment]
It works! Well it doesn't complain about API mismatch anymore, but i've run into the next issue. Closing this one and opening another.
