### ISSUE TITLE
[Feature] Ability to ignore libraries in the TBA Sonarr script

### ISSUE THREAD

**Issue by Egrirt** [goose-ws/bash-scripts#8]
Please include a clear and concise description of what you would like, and any steps or thoughts you have on how to achieve it.

I would like to see the ability to completely ignore entire libraries or root folders. The reason behind it is that I have a separate library for PT-PT shows (soap operas) that never gets updated from TBA.

Thanks for the script :)

**Comment by goose-ws** [comment]
Per my own testing this functionality should now be added. Let me know if not.

**Comment by Egrirt** [comment]
Working great! Thanks :)
